# --- Day 4: Printing Department ---

The rolls of paper (@) are arranged on a large grid; the Elves even have a helpful diagram (your puzzle input) indicating where everything is located.

For example:
```
..@@.@@@@.
@@@.@.@.@@
@@@@@.@.@@
@.@@@@..@.
@@.@@@@.@@
.@@@@@@@.@
.@.@.@.@@@
@.@@@.@@@@
.@@@@@@@@.
@.@.@@@.@.
```
The forklifts can only access a roll of paper if there are fewer than four rolls of paper in the eight adjacent positions. If you can figure out which rolls of paper the forklifts can access, they'll spend less time looking and more time breaking down the wall to the cafeteria.

In this example, there are 13 rolls of paper that can be accessed by a forklift (marked with x):
```txt
..xx.xx@x.
x@@.@.@.@@
@@@@@.x.@@
@.@@@@..@.
x@.@@@@.@x
.@@@@@@@.@
.@.@.@.@@@
x.@@@.@@@@
.@@@@@@@@.
x.x.@@@.x.
```
Consider your complete diagram of the paper roll locations. How many rolls of paper can be accessed by a forklift?

In [ ]:
from fastcore.utils import L
from aocd import get_data

inp = get_data(day=4, year=2025)
samp = '''..@@.@@@@.
@@@.@.@.@@
@@@@@.@.@@
@.@@@@..@.
@@.@@@@.@@
.@@@@@@@.@
.@.@.@.@@@
@.@@@.@@@@
.@@@@@@@@.
@.@.@@@.@.'''
samp

'..@@.@@@@.\n@@@.@.@.@@\n@@@@@.@.@@\n@.@@@@..@.\n@@.@@@@.@@\n.@@@@@@@.@\n.@.@.@.@@@\n@.@@@.@@@@\n.@@@@@@@@.\n@.@.@@@.@.'

In [ ]:
xs = samp.splitlines()
xs

['..@@.@@@@.',
 '@@@.@.@.@@',
 '@@@@@.@.@@',
 '@.@@@@..@.',
 '@@.@@@@.@@',
 '.@@@@@@@.@',
 '.@.@.@.@@@',
 '@.@@@.@@@@',
 '.@@@@@@@@.',
 '@.@.@@@.@.']

In [ ]:
x = xs[0]
x

'..@@.@@@@.'

In [ ]:
def parse_c(c):
    if c == '.': return 0
    if c == '@': return 1
    return None
parse_c('@'), parse_c('.')

(1, 0)

In [ ]:
def parse_row(x):
    return L(list(x)).map(parse_c)
parse_row(x)

[0, 0, 1, 1, 0, 1, 1, 1, 1, 0]

In [ ]:
def parse(s):
    xs = s.splitlines()
    return L(xs).map(parse_row)
x = parse(samp)
x

[[0, 0, 1, 1, 0, 1, 1, 1, 1, 0], [1, 1, 1, 0, 1, 0, 1, 0, 1, 1], [1, 1, 1, 1, 1, 0, 1, 0, 1, 1], [1, 0, 1, 1, 1, 1, 0, 0, 1, 0], [1, 1, 0, 1, 1, 1, 1, 0, 1, 1], [0, 1, 1, 1, 1, 1, 1, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 1, 1], [1, 0, 1, 1, 1, 0, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1, 1, 1, 1, 0], [1, 0, 1, 0, 1, 1, 1, 0, 1, 0]]

In [ ]:
import numpy as np

g = np.array(x)
g

array([[0, 0, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 1, 0, 1, 0]])

In [ ]:
gp = np.pad(g, 1)
gp

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

How can I in numpy easily get 8 items surrounding a given position in a 2D array?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Great question! In NumPy, you can use slicing to extract the 8 surrounding neighbors of a position. Here's the pattern:

For a position at `(i, j)`, the 8 neighbors are in a 3x3 grid centered on that position. You can get them with:

```python
neighbors = gp[i-1:i+2, j-1:j+2]
```

This gives you a 3x3 array that includes the center position plus the 8 surrounding cells.

If you only want the 8 neighbors (excluding the center), you could either flatten and skip the middle element, or access specific positions. For counting neighbors (which seems relevant to your problem), you might do:

```python
neighbor_sum = gp[i-1:i+2, j-1:j+2].sum() - gp[i, j]
```

This sums all 9 cells and subtracts the center one.

Does this approach make sense for what you're trying to do with the forklift problem?

How can I exclude the middle element?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

There are a few ways! Here are two common approaches:

1. **Flatten and skip the middle index:**
   ```python
   neighbors = gp[i-1:i+2, j-1:j+2].flatten()
   neighbors = np.delete(neighbors, 4)  # index 4 is the center in a flattened 3x3
   ```

2. **Use a boolean mask:**
   ```python
   mask = np.ones((3, 3), dtype=bool)
   mask[1, 1] = False
   neighbors = gp[i-1:i+2, j-1:j+2][mask]
   ```

Which approach seems clearer to you, or would you like to see another way?

In [ ]:
i = 2
j = 1

In [ ]:
def _neighbors(g, i, j):
    mask = np.ones((3, 3), dtype=bool)
    mask[1, 1] = False
    return g[i-1:i+2, j-1:j+2][mask]
_neighbors(gp, 2, 1)

array([0, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
cnt = 0
for i in range(1, gp.shape[0]-1):
    for j in range(1, gp.shape[1]-1):
        if gp[i, j] == 1 and _neighbors(gp, i, j).sum() < 4:
            cnt += 1
cnt


13

In [ ]:
def count_rolls(gp):
    ps = []
    for i in range(1, gp.shape[0]-1):
        for j in range(1, gp.shape[1]-1):
            if gp[i, j] == 1 and _neighbors(gp, i, j).sum() < 4:
                ps.append((i, j))
    return ps
len(count_rolls(gp))

13

In [ ]:
def solve(inp):
    x = parse(inp)
    g = np.array(x)
    gp = np.pad(g, 1)
    return len(count_rolls(gp))
solve(samp)

13

In [ ]:
solve(inp)

1533

# --- Part Two ---

Now, the Elves just need help accessing as much of the paper as they can.

Once a roll of paper can be accessed by a forklift, it can be removed. Once a roll of paper is removed, the forklifts might be able to access more rolls of paper, which they might also be able to remove. How many total rolls of paper could the Elves remove if they keep repeating this process?

Starting with the same example as above, here is one way you could remove as many rolls of paper as possible, using highlighted @ to indicate that a roll of paper is about to be removed, and using x to indicate that a roll of paper was just removed:

Initial state:
```
..@@.@@@@.
@@@.@.@.@@
@@@@@.@.@@
@.@@@@..@.
@@.@@@@.@@
.@@@@@@@.@
.@.@.@.@@@
@.@@@.@@@@
.@@@@@@@@.
@.@.@@@.@.

Remove 13 rolls of paper:
..xx.xx@x.
x@@.@.@.@@
@@@@@.x.@@
@.@@@@..@.
x@.@@@@.@x
.@@@@@@@.@
.@.@.@.@@@
x.@@@.@@@@
.@@@@@@@@.
x.x.@@@.x.

Remove 12 rolls of paper:
.......x..
.@@.x.x.@x
x@@@@...@@
x.@@@@..x.
.@.@@@@.x.
.x@@@@@@.x
.x.@.@.@@@
..@@@.@@@@
.x@@@@@@@.
....@@@...

Remove 7 rolls of paper:
..........
.x@.....x.
.@@@@...xx
..@@@@....
.x.@@@@...
..@@@@@@..
...@.@.@@x
..@@@.@@@@
..x@@@@@@.
....@@@...

Remove 5 rolls of paper:
..........
..x.......
.x@@@.....
..@@@@....
...@@@@...
..x@@@@@..
...@.@.@@.
..x@@.@@@x
...@@@@@@.
....@@@...

Remove 2 rolls of paper:
..........
..........
..x@@.....
..@@@@....
...@@@@...
...@@@@@..
...@.@.@@.
...@@.@@@.
...@@@@@x.
....@@@...

Remove 1 roll of paper:
..........
..........
...@@.....
..x@@@....
...@@@@...
...@@@@@..
...@.@.@@.
...@@.@@@.
...@@@@@..
....@@@...

Remove 1 roll of paper:
..........
..........
...x@.....
...@@@....
...@@@@...
...@@@@@..
...@.@.@@.
...@@.@@@.
...@@@@@..
....@@@...

Remove 1 roll of paper:
..........
..........
....x.....
...@@@....
...@@@@...
...@@@@@..
...@.@.@@.
...@@.@@@.
...@@@@@..
....@@@...

Remove 1 roll of paper:
..........
..........
..........
...x@@....
...@@@@...
...@@@@@..
...@.@.@@.
...@@.@@@.
...@@@@@..
....@@@...
```
Stop once no more rolls of paper are accessible by a forklift. In this example, a total of 43 rolls of paper can be removed.

Start with your original diagram. How many rolls of paper in total can be removed by the Elves and their forklifts?

In [ ]:
x = parse(samp)
g = np.array(x)
gp = np.pad(g, 1)
ps = count_rolls(gp)
ps

[(1, 3),
 (1, 4),
 (1, 6),
 (1, 7),
 (1, 9),
 (2, 1),
 (3, 7),
 (5, 1),
 (5, 10),
 (8, 1),
 (10, 1),
 (10, 3),
 (10, 9)]

In [ ]:
for o in ps: gp[o] = 0
gp

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
x = parse(samp)
g = np.array(x)
gp = np.pad(g, 1)
gp_orig = gp.copy()
cnt = 0
while True:
    ps = count_rolls(gp)
    if not ps: break
    for o in ps: gp[o] = 0
gp

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
gp.sum()

np.int64(28)

In [ ]:
gp_orig.sum() - gp.sum()

np.int64(43)

In [ ]:
def solve(inp):
    x = parse(inp)
    g = np.array(x)
    gp = np.pad(g, 1)
    gp_orig = gp.copy()
    cnt = 0
    while True:
        ps = count_rolls(gp)
        if not ps: break
        for o in ps: gp[o] = 0
    return int(gp_orig.sum() - gp.sum())
solve(samp)

43

In [ ]:
solve(inp)

9206