# --- Day 6: Trash Compactor ---

Cephalopod math doesn't look that different from normal math. The math worksheet (your puzzle input) consists of a list of problems; each problem has a group of numbers that need to be either added (+) or multiplied (*) together.

However, the problems are arranged a little strangely; they seem to be presented next to each other in a very long horizontal list. For example:
```
123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +  
```
Each problem's numbers are arranged vertically; at the bottom of the problem is the symbol for the operation that needs to be performed. Problems are separated by a full column of only spaces. The left/right alignment of numbers within each problem can be ignored.

So, this worksheet contains four problems:
```
123 * 45 * 6 = 33210
328 + 64 + 98 = 490
51 * 387 * 215 = 4243455
64 + 23 + 314 = 401
```
To check their work, cephalopod students are given the grand total of adding together all of the answers to the individual problems. In this worksheet, the grand total is 33210 + 490 + 4243455 + 401 = 4277556.

Of course, the actual worksheet is much wider. You'll need to make sure to unroll it completely so that you can read the problems clearly.

Solve the problems on the math worksheet. What is the grand total found by adding together all of the answers to the individual problems?

In [ ]:
from fastcore.utils import L
from aocd import get_data

inp = get_data(day=6, year=2025)
samp = '''123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +  '''
samp

'123 328  51 64 \n 45 64  387 23 \n  6 98  215 314\n*   +   *   +  '

Please summarize the assignment for me.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Looking at this Advent of Code problem, here's what you need to do:

**The Task:**
You have a math worksheet where problems are arranged in vertical columns across a horizontal layout. Each column is either an addition or multiplication problem, and you need to:

1. Parse the vertical columns to identify separate problems
2. Extract the numbers in each column (reading top to bottom)
3. Apply the operation shown at the bottom of each column (* or +)
4. Calculate each problem's answer
5. Add all the answers together for a grand total

**Key points:**
- Problems are separated by columns of only spaces
- Numbers can be right/left aligned within their column (ignore alignment)
- The operation symbol is at the bottom of each column

In the sample, there are 4 problems that give answers of 33210, 490, 4243455, and 401, which sum to 4277556.

You already have the sample data loaded and the actual puzzle input ready. How would you like to approach parsing this? Do you have initial thoughts on how to identify the separate columns?

In [ ]:
xs = samp.splitlines()
xs

['123 328  51 64 ', ' 45 64  387 23 ', '  6 98  215 314', '*   +   *   +  ']

In [ ]:
x = xs[0]
x.split()

['123', '328', '51', '64']

In [ ]:
def parse_num_line(x): return L(x.split()).map(int)
parse_num_line(x)

[123, 328, 51, 64]

In [ ]:
def parse_nums(xs):
    return L(xs).map(parse_num_line)
parse_nums(xs[:-1])

[[123, 328, 51, 64], [45, 64, 387, 23], [6, 98, 215, 314]]

In [ ]:
import numpy as np
arr = np.array(parse_nums(xs[:-1]))
arr.T

array([[123,  45,   6],
       [328,  64,  98],
       [ 51, 387, 215],
       [ 64,  23, 314]])

How can I apply a product to each row of an array?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

You can use `np.prod()` with the `axis` parameter! To apply the product across each row, you'd use `axis=1`:

```python
np.prod(arr.T, axis=1)
```

This will multiply all the values in each row together. The `axis=1` tells NumPy to operate along the columns within each row (collapsing the columns).

Want to try it out and see if it gives you the expected results for the multiplication problems?

In [ ]:
np.prod(arr.T, axis=1)

array([  33210, 2057216, 4243455,  462208])

In [ ]:
np.sum(arr.T, axis=1)

array([174, 490, 653, 401])

In [ ]:
def parse_fn_line(x):
    return L(x.split()).map(lambda c: np.sum if c == '+' else np.prod)
fns = parse_fn_line(xs[-1])
fns

[<function prod at 0x7b410c99aab0>, <function sum at 0x7b410c9994f0>, <function prod at 0x7b410c99aab0>, <function sum at 0x7b410c9994f0>]

Can I easily apply funtions in `fns` to each row in `arr.T`?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Yes! You can use a list comprehension or loop through them together. Since you have a function for each row, you can zip them:

```python
[fn(row) for fn, row in zip(fns, arr.T)]
```

This pairs each function with its corresponding row and applies it. Does this approach make sense for what you're trying to do?

In [ ]:
[fn(row) for fn, row in zip(fns, arr.T)]

[np.int64(33210), np.int64(490), np.int64(4243455), np.int64(401)]

In [ ]:
int(sum([fn(row) for fn, row in zip(fns, arr.T)]))

4277556

Please combine the functions above to a single solve function.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Here's a combined solve function:

```python
def solve(inp):
    xs = inp.splitlines()
    arr = np.array(L(xs[:-1]).map(parse_num_line))
    fns = parse_fn_line(xs[-1])
    return int(sum([fn(row) for fn, row in zip(fns, arr.T)]))
```

This brings together all your parsing and calculation steps. Want to test it on both the sample and your actual input?

In [ ]:
def solve(inp):
    xs = inp.splitlines()
    arr = np.array(L(xs[:-1]).map(parse_num_line))
    fns = parse_fn_line(xs[-1])
    return int(sum([fn(row) for fn, row in zip(fns, arr.T)]))
solve(samp)

4277556

In [ ]:
solve(inp)

3525371263915

# --- Part Two ---

Cephalopod math is written right-to-left in columns. Each number is given in its own column, with the most significant digit at the top and the least significant digit at the bottom. (Problems are still separated with a column consisting only of spaces, and the symbol at the bottom of the problem is still the operator to use.)

Here's the example worksheet again:
```
123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +  
```
Reading the problems right-to-left one column at a time, the problems are now quite different:

- The rightmost problem is 4 + 431 + 623 = 1058
- The second problem from the right is 175 * 581 * 32 = 3253600
- The third problem from the right is 8 + 248 + 369 = 625
- Finally, the leftmost problem is 356 * 24 * 1 = 8544

Now, the grand total is 1058 + 3253600 + 625 + 8544 = 3263827.

Solve the problems on the math worksheet again. What is the grand total found by adding together all of the answers to the individual problems?

Please summarize part 2 for me.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

**Part 2 Changes:**

The numbers are now read **vertically** within each column (top to bottom gives you the digits of a single number), and the problems are read **right-to-left** across the worksheet.

So in the example:
- The rightmost column `4, 3, 1` forms the number 431 (reading digits top-to-bottom)
- Each column within a problem is a separate number
- Problems are still separated by space-only columns
- You still apply the operator at the bottom

Instead of `123 * 45 * 6`, the leftmost problem is now `1 * 24 * 356` (reading the three number columns right-to-left, with each number's digits read top-to-bottom).

The new grand total for the sample is 3263827.

How are you thinking about modifying your `solve` function to handle this different interpretation?

I think I will need to adjust parsing function because now a position of a blank is significant.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Exactly right! In Part 1, you could just use `split()` which ignored where the spaces were. Now you need to track the exact column positions because:

1. Spaces separate different problems
2. Non-space characters in the same column position belong to the same number

How are you thinking about identifying which characters belong to the same column? Do you have an approach in mind, or would you like to discuss some options?

I think I can use the last line with operations. Looking at the number of blanks there should give me the width of each column

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

That's a clever insight! The operations line does show you the structure. You can identify where the operators are positioned, and the gaps between them (the spaces) tell you where one problem ends and another begins.

How are you planning to use this information? Are you thinking of:
- Finding the column indices of each operator?
- Grouping columns based on proximity to each operator?
- Something else?

What's your next step?

In [ ]:
x = xs[-1].replace(' ', '.')
x


'*...+...*...+..'

I want to get indexes of '*' and '+' in the `x` string.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

You can use `enumerate()` to get both the index and character:

```python
[i for i, c in enumerate(x) if c in '*+']
```

This will give you a list of all the column positions where operators appear. Want to try it?

In [ ]:
start_idx = [i for i, c in enumerate(x) if c in '*+']
start_idx

[0, 4, 8, 12]

In [ ]:
end_idx = L(start_idx[1:]).map(lambda x: x - 1) + [len(x)]
end_idx

[3, 7, 11, 15]

In [ ]:
idxs = L(start_idx, end_idx).zip()
idxs

[(0, 3), (4, 7), (8, 11), (12, 15)]

In [ ]:
x = '*..X+..X*..X+..'
x

'*..X+..X*..X+..'

In [ ]:
def substr(t, s): return s[t[0]:t[1]]
substr((0, 3), x)

'*..'

In [ ]:
idxs.map(substr, s=x)

['*..', '+..', '*..', '+..']

In [ ]:
xs[0]

'123 328  51 64 '

In [ ]:
idxs.map(substr, s=xs[0])

['123', '328', ' 51', '64 ']

In [ ]:
def parse_col_rngs(x):
    start_idx = [i for i, c in enumerate(x) if c in '*+']
    end_idx = L(start_idx[1:]).map(lambda x: x - 1) + [len(x)]
    return L(start_idx, end_idx).zip()
idxs = parse_col_rngs(xs[-1])
idxs

[(0, 3), (4, 7), (8, 11), (12, 15)]

In [ ]:
idxs.map(substr, s=xs[0])

['123', '328', ' 51', '64 ']

In [ ]:
def parse_num_line(s, idxs):
    return idxs.map(substr, s=s)
parse_num_line(xs[0], idxs)

['123', '328', ' 51', '64 ']

In [ ]:
from math import prod

def parse_fn_line(x):
    return L(x.split()).map(lambda c: sum if c == '+' else prod)
parse_fn_line('*   +   *   +  ')

[<built-in function prod>, <built-in function sum>, <built-in function prod>, <built-in function sum>]

How can I fix the error?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

The `product` function is in the `math` module, not `fastcore`. You can use:

```python
from math import prod
```

Then change `product` to `prod` in your lambda. Want to try that?

In [ ]:
def parse(inp):
    xs = inp.splitlines()
    idxs = parse_col_rngs(xs[-1])
    nums = L(xs[:-1]).map(parse_num_line, idxs=idxs)
    fns = parse_fn_line(xs[-1])
    return nums, fns
ps, fns = parse(samp)
ps, fns

([['123', '328', ' 51', '64 '], [' 45', '64 ', '387', '23 '], ['  6', '98 ', '215', '314']],
 [<built-in function prod>, <built-in function sum>, <built-in function prod>, <built-in function sum>])

In [ ]:
qs = L(ps).zip()
qs

[('123', ' 45', '  6'), ('328', '64 ', '98 '), (' 51', '387', '215'), ('64 ', '23 ', '314')]

In [ ]:
q = qs[0]
q

In [ ]:
L(q).zip()

In [ ]:
L(q).zip().map(lambda t: ''.join(t))

In [ ]:
L(q).zip().map(lambda t: ''.join(t)).map(int)

In [ ]:
def transform_col(q):
    return L(q).zip().map(lambda t: ''.join(t)).map(int)
transform_col(q)

In [ ]:
def transform_nums(ps):
    qs = L(ps).zip()
    return qs.map(transform_col)
ns = transform_nums(ps)
ns

Where we are at?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

You're making great progress! Here's where you are:

**Done:**
- `parse_col_rngs()` - finds column ranges based on operator positions
- `parse()` - extracts string chunks for each column and the operators
- `transform_nums()` - reads digits vertically to form the actual numbers

**Current output:**
Your `transform_nums(ps)` gives `[[1, 24, 356], [369, 248, 8], [32, 581, 175], [623, 431, 4]]`

**Remaining:**
You need to read the problems right-to-left, apply each function (from `fns`), and sum the results. Looking at the expected output for the sample, the rightmost problem should be `4 + 431 + 623 = 1058`.

How do you want to handle the right-to-left ordering?

In [ ]:
fns

In [ ]:
L(fns, ns).zip()

In [ ]:
L(fns, ns).zip().map(lambda t: t[0](t[1]))

In [ ]:
L(fns, ns).zip().map(lambda t: t[0](t[1])).sum()

Plese combine the functions above into solve function.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Here's the combined solve function:

```python
def solve(inp):
    ps, fns = parse(inp)
    ns = transform_nums(ps)
    return L(fns, ns).zip().map(lambda t: t[0](t[1])).sum()
```

Want to test it on both the sample and your actual input?

In [ ]:
def solve(inp):
    ps, fns = parse(inp)
    ns = transform_nums(ps)
    return L(fns, ns).zip().map(lambda t: t[0](t[1])).sum()
solve(samp)

In [ ]:
solve(inp)

Can you suggest improvements to the current solution? How can I make more readable?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

A few ideas to consider:

1. **Unpack the tuple in the lambda** - Instead of `lambda t: t[0](t[1])`, you could use `starmap` or unpack more clearly

2. **Name intermediate results** - The `parse` function returns `(ps, fns)` but `ps` isn't very descriptive. Maybe `raw_cols` or `str_chunks`?

3. **Combine parse and transform** - Since `transform_nums` always follows `parse`, you could have `parse` return the fully transformed numbers directly

4. **Add a docstring** - A brief comment explaining the vertical column reading would help future readers

Which of these interests you most? Or is there a specific part that feels unclear to you when you read it back?

Show me the code to Unpack the tuple in the lambda.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

You can use `starmap` from fastcore, which automatically unpacks tuples as arguments:

```python
L(fns, ns).zip().starmap(lambda fn, nums: fn(nums)).sum()
```

This reads more clearly - you can see `fn` is applied to `nums` directly.

In [ ]:
def solve(inp):
    ps, fns = parse(inp)
    ns = transform_nums(ps)
    return L(fns, ns).zip().starmap(lambda fn, nums: fn(nums)).sum()
solve(samp)