## --- Day 10: Hoof It ---

Perhaps you can help fill in the missing hiking trails?

The topographic map indicates the height at each position using a scale from 0 (lowest) to 9 (highest). For example:

In [ ]:
import sys
sys.path.append('..')
from utils import *

inp = get_data(day=10, year=2024)
samp = '''0123
1234
8765
9876'''
print(samp)

0123
1234
8765
9876


Based on un-scorched scraps of the book, you determine that a good hiking trail is as long as possible and has an even, gradual, uphill slope. For all practical purposes, this means that a hiking trail is any path that starts at height 0, ends at height 9, and always increases by a height of exactly 1 at each step. Hiking trails never include diagonal steps - only up, down, left, or right (from the perspective of the map).

You look up from the map and notice that the reindeer has helpfully begun to construct a small pile of pencils, markers, rulers, compasses, stickers, and other equipment you might need to update the map with hiking trails.

A trailhead is any position that starts one or more hiking trails - here, these positions will always have height 0. Assembling more fragments of pages, you establish that a trailhead's score is the number of 9-height positions reachable from that trailhead via a hiking trail. In the above example, the single trailhead in the top left corner has a score of 1 because it can reach a single 9 (the one in the bottom left).

This trailhead has a score of 2:
```
...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9
```
(The positions marked . are impassable tiles to simplify these examples; they do not appear on your actual topographic map.)

This trailhead has a score of 4 because every 9 is reachable via a hiking trail except the one immediately to the left of the trailhead:
```
..90..9
...1.98
...2..7
6543456
765.987
876....
987....
```
This topographic map contains two trailheads; the trailhead at the top has a score of 1, while the trailhead at the bottom has a score of 2:
```
10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01
```
Here's a larger example:

In [ ]:
samp2 = '''89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732'''

This larger example has 9 trailheads. Considering the trailheads in reading order, they have scores of 5, 6, 5, 3, 1, 3, 5, 3, and 5. Adding these scores together, the sum of the scores of all trailheads is 36.

The reindeer gleefully carries over a protractor and adds it to the pile. What is the sum of the scores of all trailheads on your topographic map?

Can you summarize the task for me?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Sure! Here's what you need to do:

You have a topographic map with heights from 0 to 9. You need to find all the **hiking trails** and calculate a score.

**Key rules:**
- A hiking trail starts at height 0 and ends at height 9
- Each step must increase by exactly 1 (0→1→2→...→9)
- You can only move up, down, left, or right (no diagonals)
- A **trailhead** is any position with height 0
- A trailhead's **score** is the number of distinct 9-height positions you can reach from it via valid hiking trails

**Your task:** Find the sum of all trailhead scores on your map.

For example, in the larger sample, there are 9 trailheads with scores that add up to 36.

Does that make sense? Would you like to talk about how to approach solving this?

Yes, let's discuss the approach.
This looks like a graph problem:
- Numbers are the nodes.
- There's an oriented edge between two nodes only if they are one position left/right/up/down from each other AND the source node has a number exactly one lower than the target node.
- The goal would be to get the number of distinct 9 nodes reachable from all 0 nodes.
Is that correct?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Yes, that's exactly right! You've nailed the graph interpretation:

- Nodes are the positions on the map (with their heights)
- Directed edges exist only between adjacent positions where height increases by exactly 1
- For each 0 node (trailhead), count how many distinct 9 nodes are reachable
- Sum all those counts

This is a classic graph reachability problem. 

What algorithm are you thinking of using to find all reachable 9s from each 0? There are a few good options here.

What about using Floyd-Warshall algorithm?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Floyd-Warshall would work, but it might be overkill for this problem. Here's why:

Floyd-Warshall computes **all-pairs shortest paths** - it tells you the shortest path between every pair of nodes. That's O(n³) time complexity where n is the number of nodes (which could be up to 10,000+ positions on your map).

For this problem, you only need to know which 9s are reachable from each 0. You don't need:
- Paths between other pairs of nodes
- The actual shortest path distances

A simpler approach like **BFS** (breadth-first search) or **DFS** (depth-first search) from each trailhead would be O(V + E) per trailhead, which is much more efficient here since you have a sparse graph (each node connects to at most 4 neighbors).

What do you think? Would you like to go with BFS/DFS instead, or do you have a specific reason for considering Floyd-Warshall?

Ok, let's use DFS. Can you recommend a suitable library for that? Does NumPy or SciPy have an implementation which can be used?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Good question! For graph algorithms, **NetworkX** is the most straightforward library - it has built-in DFS and graph construction tools. It's already available in your environment.

**SciPy** also has graph algorithms in `scipy.sparse.csgraph`, including `depth_first_order` and `breadth_first_order`, but they require you to build an adjacency matrix first, which can be a bit more work.

**NumPy** doesn't have graph algorithms built-in.

That said, for this problem, implementing DFS yourself is actually quite simple and might be clearer than using a library. It's just a recursive function or a stack-based loop that explores neighbors.

Which approach appeals to you more - using NetworkX, or writing your own DFS? If you want to write it yourself, I can give you a hint about the structure.

Nice! Can you give me an example how to work with NetworkX?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Sure! Here's a basic example of using NetworkX for this type of problem:

```python
import networkx as nx

# Create a directed graph
G = nx.DiGraph()

# Add edges (from_node, to_node)
G.add_edge((0,0), (0,1))  # positions as tuples
G.add_edge((0,1), (0,2))
```

Then to find reachable nodes from a starting point, you can use:

```python
reachable = nx.descendants(G, start_node)
```

For your problem, you'd need to:
1. Parse the map into a 2D array
2. Build the graph by adding edges between adjacent positions where height increases by 1
3. For each 0 position, find all reachable 9 positions

Would you like to try building the graph from your map data? Start with parsing the input into a grid - what approach are you thinking of using for that?

Ok, here's the plan:
1. Parse the input. Split the lines, split the line into digits and convert them to numbers. Use numpy matrix to represent the map.
2. From the numpy matrix, let's extract nodes and all the oriented edges - all adjecant digits. Let's use a class to represent a node, it will contain coordinates and the value.
3. Filter only valid edges - those from a node with a value n to a node with a value n + 1.
4. Use NetworkX and find all the reachable nodes and then filter only those with value 9.
5. Get the sum.

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

That's a solid plan! A few thoughts:

**On step 2:** Do you really need a class for nodes? NetworkX can use tuples like `(row, col)` as nodes directly, and you can store the height value as a node attribute. This might be simpler than creating a custom class.

For example:
```python
G.add_node((0, 0), height=1)
```

Or you could just use `(row, col)` as the node identifier and look up heights in your numpy matrix when needed.

What do you think - would tuples work for you, or do you prefer the class approach?

In [ ]:
xs = samp.splitlines()
xs

['0123', '1234', '8765', '9876']

In [ ]:
x = xs[0]
x

'0123'

In [ ]:
L(list(x)).map(int)

(#4) [0,1,2,3]

In [ ]:
def parse_line(x):
    return L(list(x)).map(int)
parse_line(x)    

(#4) [0,1,2,3]

In [ ]:
import numpy as np

def parse(txt):
    xs = txt.splitlines()
    arr = L(xs).map(list).map(parse_line)
    return np.array(arr)
arr = parse(samp)
arr

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [8, 7, 6, 5],
       [9, 8, 7, 6]])

In [ ]:
arr2 = parse(samp2)
arr2

array([[8, 9, 0, 1, 0, 1, 2, 3],
       [7, 8, 1, 2, 1, 8, 7, 4],
       [8, 7, 4, 3, 0, 9, 6, 5],
       [9, 6, 5, 4, 9, 8, 7, 4],
       [4, 5, 6, 7, 8, 9, 0, 3],
       [3, 2, 0, 1, 9, 0, 1, 2],
       [0, 1, 3, 2, 9, 8, 0, 1],
       [1, 0, 4, 5, 6, 7, 3, 2]])

In [ ]:
ds = [(-1, 0), (1, 0), (0, -1), (0, 1)]
# len(arr[0])

How can I iterate through all positions in arr?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

There are several ways! Here are a few options:

**Option 1: Using numpy's `ndindex`**
```python
for pos in np.ndindex(arr.shape):
    row, col = pos
    value = arr[pos]
```

**Option 2: Nested loops**
```python
for row in range(len(arr)):
    for col in range(len(arr[0])):
        value = arr[row, col]
```

**Option 3: Using `np.ndenumerate`** (gives you index and value together)
```python
for pos, value in np.ndenumerate(arr):
    row, col = pos
```

Which style do you prefer? The first one is nice because it gives you positions as tuples, which works well with NetworkX nodes.

In [ ]:
L(np.ndenumerate(arr))

(#16) [((0, 0), np.int64(0)),((0, 1), np.int64(1)),((0, 2), np.int64(2)),((0, 3), np.int64(3)),((1, 0), np.int64(1)),((1, 1), np.int64(2)),((1, 2), np.int64(3)),((1, 3), np.int64(4)),((2, 0), np.int64(8)),((2, 1), np.int64(7)),((2, 2), np.int64(6)),((2, 3), np.int64(5)),((3, 0), np.int64(9)),((3, 1), np.int64(8)),((3, 2), np.int64(7)),((3, 3), np.int64(6))]

In [ ]:
def _nodes(arr):
    return L(np.ndindex(arr.shape))
_nodes(arr)

(#16) [(0, 0),(0, 1),(0, 2),(0, 3),(1, 0),(1, 1),(1, 2),(1, 3),(2, 0),(2, 1),(2, 2),(2, 3),(3, 0),(3, 1),(3, 2),(3, 3)]

In [ ]:
def in_bounds(pos, arr):
    row, col = pos
    return 0 <= row < arr.shape[0] and 0 <= col < arr.shape[1]

In [ ]:
p = (3, 0)
L(ds).map(lambda d: (p[0] + d[0], p[1] + d[1]))

(#4) [(2, 0),(4, 0),(3, -1),(3, 1)]

In [ ]:
p = (3, 0)
L(ds).map(lambda d: (p[0] + d[0], p[1] + d[1])).filter(in_bounds, arr=arr)

(#2) [(2, 0),(3, 1)]

In [ ]:
def _neighbors(p, arr):
    ds = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    return L(ds).map(lambda d: (p[0] + d[0], p[1] + d[1])).filter(in_bounds, arr=arr)
_neighbors(p, arr)

(#2) [(2, 0),(3, 1)]

In [ ]:
L(np.ndindex(arr.shape))

(#16) [(0, 0),(0, 1),(0, 2),(0, 3),(1, 0),(1, 1),(1, 2),(1, 3),(2, 0),(2, 1),(2, 2),(2, 3),(3, 0),(3, 1),(3, 2),(3, 3)]

In [ ]:
ps = L(np.ndindex(arr.shape))
ps.map(_neighbors, arr=arr)

(#16) [[(1, 0), (0, 1)],[(1, 1), (0, 0), (0, 2)],[(1, 2), (0, 1), (0, 3)],[(1, 3), (0, 2)],[(0, 0), (2, 0), (1, 1)],[(0, 1), (2, 1), (1, 0), (1, 2)],[(0, 2), (2, 2), (1, 1), (1, 3)],[(0, 3), (2, 3), (1, 2)],[(1, 0), (3, 0), (2, 1)],[(1, 1), (3, 1), (2, 0), (2, 2)],[(1, 2), (3, 2), (2, 1), (2, 3)],[(1, 3), (3, 3), (2, 2)],[(2, 0), (3, 1)],[(2, 1), (3, 0), (3, 2)],[(2, 2), (3, 1), (3, 3)],[(2, 3), (3, 2)]]

In [ ]:
ns = ps.map(_neighbors, arr=arr)
ns

(#16) [[(1, 0), (0, 1)],[(1, 1), (0, 0), (0, 2)],[(1, 2), (0, 1), (0, 3)],[(1, 3), (0, 2)],[(0, 0), (2, 0), (1, 1)],[(0, 1), (2, 1), (1, 0), (1, 2)],[(0, 2), (2, 2), (1, 1), (1, 3)],[(0, 3), (2, 3), (1, 2)],[(1, 0), (3, 0), (2, 1)],[(1, 1), (3, 1), (2, 0), (2, 2)],[(1, 2), (3, 2), (2, 1), (2, 3)],[(1, 3), (3, 3), (2, 2)],[(2, 0), (3, 1)],[(2, 1), (3, 0), (3, 2)],[(2, 2), (3, 1), (3, 3)],[(2, 3), (3, 2)]]

In [ ]:
L(ps, ns).zip()

(#16) [((0, 0), [(1, 0), (0, 1)]),((0, 1), [(1, 1), (0, 0), (0, 2)]),((0, 2), [(1, 2), (0, 1), (0, 3)]),((0, 3), [(1, 3), (0, 2)]),((1, 0), [(0, 0), (2, 0), (1, 1)]),((1, 1), [(0, 1), (2, 1), (1, 0), (1, 2)]),((1, 2), [(0, 2), (2, 2), (1, 1), (1, 3)]),((1, 3), [(0, 3), (2, 3), (1, 2)]),((2, 0), [(1, 0), (3, 0), (2, 1)]),((2, 1), [(1, 1), (3, 1), (2, 0), (2, 2)]),((2, 2), [(1, 2), (3, 2), (2, 1), (2, 3)]),((2, 3), [(1, 3), (3, 3), (2, 2)]),((3, 0), [(2, 0), (3, 1)]),((3, 1), [(2, 1), (3, 0), (3, 2)]),((3, 2), [(2, 2), (3, 1), (3, 3)]),((3, 3), [(2, 3), (3, 2)])]

How can I get a list of edges from ps and ns?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

You want to create edges from each position to each of its neighbors. You can use a nested map or a list comprehension.

Here are a couple of approaches:

**Using nested map:**
```python
edges = L(ps, ns).zip().map(lambda p_ns: [(p_ns[0], n) for n in p_ns[1]]).concat()
```

**Or unpack the tuple:**
```python
edges = L(ps, ns).zip().map(lambda x: [(x[0], n) for n in x[1]]).concat()
```

This creates a list of `(from_pos, to_pos)` tuples for all edges. The `concat()` flattens the nested lists.

Does this make sense? Give it a try!

In [ ]:
def _edges(arr) :
    ps = L(np.ndindex(arr.shape))
    ns = ps.map(_neighbors, arr=arr)
    return L(ps, ns).zip().map(lambda x: [(x[0], n) for n in x[1]]).concat()
es = _edges(arr)
es

(#48) [((0, 0), (1, 0)),((0, 0), (0, 1)),((0, 1), (1, 1)),((0, 1), (0, 0)),((0, 1), (0, 2)),((0, 2), (1, 2)),((0, 2), (0, 1)),((0, 2), (0, 3)),((0, 3), (1, 3)),((0, 3), (0, 2)),((1, 0), (0, 0)),((1, 0), (2, 0)),((1, 0), (1, 1)),((1, 1), (0, 1)),((1, 1), (2, 1)),((1, 1), (1, 0)),((1, 1), (1, 2)),((1, 2), (0, 2)),((1, 2), (2, 2)),((1, 2), (1, 1))...]

In [ ]:
arr

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [8, 7, 6, 5],
       [9, 8, 7, 6]])

In [ ]:
def is_valid_edge(e, arr):
    n1, n2 = e
    return arr[n1] == arr[n2] - 1
is_valid_edge(((0, 0), (0, 1)), arr), is_valid_edge(((2, 0), (2, 1)), arr)


(np.True_, np.False_)

In [ ]:
es.filter(is_valid_edge, arr=arr)

(#21) [((0, 0), (1, 0)),((0, 0), (0, 1)),((0, 1), (1, 1)),((0, 1), (0, 2)),((0, 2), (1, 2)),((0, 2), (0, 3)),((0, 3), (1, 3)),((1, 0), (1, 1)),((1, 1), (1, 2)),((1, 2), (1, 3)),((1, 3), (2, 3)),((2, 0), (3, 0)),((2, 1), (3, 1)),((2, 1), (2, 0)),((2, 2), (3, 2)),((2, 2), (2, 1)),((2, 3), (3, 3)),((2, 3), (2, 2)),((3, 1), (3, 0)),((3, 2), (3, 1))...]

Where we are at?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Great progress! Here's where you are:

1. ✅ Parsed the input into a numpy array
2. ✅ Generated all positions and their neighbors
3. ✅ Created all possible edges
4. ✅ Filtered to keep only valid edges (where height increases by exactly 1)

**Next steps:**
5. Build the NetworkX graph from your valid edges
6. Find all positions with height 0 (trailheads)
7. For each trailhead, find reachable positions with height 9
8. Sum up the scores

Want to tackle step 5 - building the graph with NetworkX?

In [ ]:
import networkx as nx

# Create a directed graph
G = nx.DiGraph()

for n in _nodes(arr): G.add_node(n, height=arr[n])
for e in _edges(arr).filter(is_valid_edge, arr=arr): G.add_edge(*e)

reachable = nx.descendants(G, (0,0))
reachable

{(0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)}

In [ ]:
def _graph(arr):
    # Create a directed graph
    g = nx.DiGraph()
    # for n in _nodes(arr): g.add_node(n, height=arr[n])
    for e in _edges(arr).filter(is_valid_edge, arr=arr): g.add_edge(*e)
    return g

g = _graph(arr)
nx.descendants(g, (0, 0))

{(0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)}

In [ ]:
def _descendants(p, g): return nx.descendants(g, p)
_descendants((0, 0), g)

{(0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)}

How can I get all positions with value 0 in arr?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

You can use `np.where` or `np.argwhere` to find positions where the condition is true.

**Using `np.argwhere`** (returns array of coordinates):
```python
np.argwhere(arr == 0)
```

This gives you an array where each row is a `[row, col]` pair. You can convert to tuples if needed:
```python
[tuple(pos) for pos in np.argwhere(arr == 0)]
```

Give it a try! What do you get for your sample array?

In [ ]:
np.argwhere(arr == 0)

array([[0, 0]])

In [ ]:
np.argwhere(arr == 9)

array([[3, 0]])

In [ ]:
zeros = np.argwhere(arr == 0)
nines = np.argwhere(arr == 9)
zeros, nines

(array([[0, 0]]), array([[3, 0]]))

In [ ]:
from fastcore.basics import tuplify

L(zeros.tolist()).map(tuplify)

(#1) [(0, 0)]

In [ ]:
zeros = L(np.argwhere(arr == 0).tolist()).map(tuplify)
nines = L(np.argwhere(arr == 9).tolist()).map(tuplify)
zeros, nines

((#1) [(0, 0)], (#1) [(3, 0)])

In [ ]:
zeros.map(_descendants, g=g).concat()

(#15) [(0, 1),(1, 2),(2, 1),(3, 1),(1, 1),(0, 3),(2, 0),(3, 0),(2, 3),(0, 2),(3, 3),(2, 2),(1, 0),(3, 2),(1, 3)]

In [ ]:
set(zeros.map(_descendants, g=g).concat()) & set(nines)

{(3, 0)}

In [ ]:
def _score(zero, g, nines):
    return len(_descendants(zero, g) & nines)

In [ ]:
def solve(inp):
    arr = parse(inp)
    es = _edges(arr)
    g = _graph(arr)
    zeros = L(np.argwhere(arr == 0).tolist()).map(tuplify)
    nines = set(L(np.argwhere(arr == 9).tolist()).map(tuplify))
    return zeros.map(_score, g=g, nines=nines).sum()
solve(samp)

1

In [ ]:
samp2 = '''89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732'''
solve(samp2)

36

In [ ]:
solve(inp)

789

# --- Part Two ---
The reindeer spends a few minutes reviewing your hiking trail map before realizing something, disappearing for a few minutes, and finally returning with yet another slightly-charred piece of paper.

The paper describes a second way to measure a trailhead called its rating. A trailhead's rating is the number of distinct hiking trails which begin at that trailhead. For example:
```
.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9....
```
The above map has a single trailhead; its rating is 3 because there are exactly three distinct hiking trails which begin at that position:
```
.....0.   .....0.   .....0.
..4321.   .....1.   .....1.
..5....   .....2.   .....2.
..6....   ..6543.   .....3.
..7....   ..7....   .....4.
..8....   ..8....   ..8765.
..9....   ..9....   ..9....
```
Here is a map containing a single trailhead with rating 13:
```
..90..9
...1.98
...2..7
6543456
765.987
876....
987....
```
This map contains a single trailhead with rating 227 (because there are 121 distinct hiking trails that lead to the 9 on the right edge and 106 that lead to the 9 on the bottom edge):
```
012345
123456
234567
345678
4.6789
56789.
```
Here's the larger example from before:
```
89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
```
Considering its trailheads in reading order, they have ratings of 20, 24, 10, 4, 1, 4, 5, 8, and 5. The sum of all trailhead ratings in this larger example topographic map is 81.

You're not sure how, but the reindeer seems to have crafted some tiny flags out of toothpicks and bits of paper and is using them to mark trailheads on your topographic map. What is the sum of the ratings of all trailheads?

Can you summarize the part 2?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Nice work on Part 1!

**Part 2 changes the scoring method:**

Instead of counting the number of **distinct 9s** reachable from each trailhead, you now need to count the number of **distinct paths** (hiking trails) from each trailhead to any 9.

So if there are multiple different ways to reach the same 9, or different 9s, each unique path counts separately.

For example, a trailhead with 3 different paths to reach 9s would have a rating of 3, even if some paths end at the same 9.

**Your task:** Find the sum of all trailhead ratings (where rating = number of distinct paths from that trailhead to any 9).

How would you modify your approach to count paths instead of reachable nodes?

Is there an algorithm for getting different paths?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Yes! There are several approaches for counting all paths between two nodes in a directed graph:

**1. DFS with path counting** - Use depth-first search, but instead of marking nodes as visited globally, you track the current path and count every time you reach a target node.

**2. NetworkX's `all_simple_paths`** - This function finds all simple paths (paths without cycles) between two nodes. You can count them.

**3. Dynamic programming** - Since your graph is a DAG (directed acyclic graph - heights only increase), you can use DP to count paths efficiently.

For this problem, since you're going from 0s to 9s and heights always increase by 1, you have a DAG, which makes this easier.

Which approach sounds most interesting to you? NetworkX's `all_simple_paths` would be the quickest to implement if you want to try that first.

Show me an example for all_simple_paths 

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Here's a basic example of how to use `all_simple_paths`:

```python
paths = nx.all_simple_paths(G, source=(0,0), target=(3,0))
list(paths)  # Convert generator to list to see all paths
```

For your problem, you'd need to find paths from each trailhead (0) to **all** 9s, not just one target. You can either:
- Call it separately for each (zero, nine) pair
- Iterate through all nines for each zero

Try it out with your sample data! What happens when you run it?

In [ ]:
def _rate_two(nine, zero, g):
    return len(list(nx.all_simple_paths(g, source=zero, target=nine)))

def _rate(zero, g, nines):
    return L(nines).map(_rate_two, zero=zero, g=g).sum()

In [ ]:
def solve2(inp):
    arr = parse(inp)
    es = _edges(arr)
    g = _graph(arr)
    zeros = L(np.argwhere(arr == 0).tolist()).map(tuplify)
    nines = set(L(np.argwhere(arr == 9).tolist()).map(tuplify))
    return zeros.map(_rate, g=g, nines=nines).sum()
solve2(samp2)

81

In [ ]:
solve2(inp)

1735